### ISSUE TITLE
Tagging issue

### ISSUE THREAD

**Issue by ianstalk** [mhemmings/revenuecat#8]
I'm not able to add the latest tag to my `go.mod` file. If I require `github.com/mhemmings/revenuecat v2.0.1` it complains that the version is invalid and "should be v0 or v1, not v2". If I require `github.com/mhemmings/revenuecat/v2 v2.0.1` it complains about non-v2 references. I would up working around it by importing the tag's commit hash, but that's obviously less than ideal.

**Comment by HaraldNordgren** [comment]
Hi @ianstalk, please verify that this works now 🤗
